config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
  resources :grammar_points
  resources :settings
  get 'grammar_points/:id/examples' => 'grammar_points#examples', as: :examples
  get 'examples' => 'grammar_points#list_examples', as: :list_examples
	

  get '/home', to:'static#home', as: :home
	root 'static#home'

  get '/network', to:'static#network'
  get '/network_HSK1', to:'static#network_HSK1'
  get '/network_HSK2', to:'static#network_HSK2'
  get '/network_HSK3', to:'static#network_HSK3'
  get '/tone_network', to:'static#tone_network'
  get '/radicals', to:'static#radicals'

  get 'grammar_tree_A1', to:'static#grammar_tree_A1'
  get 'grammar_tree_A2', to:'static#grammar_tree_A2'
  get 'grammar_tree_B1', to:'static#grammar_tree_B1'
  get 'grammar_tree_B2', to:'static#grammar_tree_B2'

  get 'flashcards/' => 'flashcards#flashcards'
  patch '/flashcards/:id/check' => 'flashcards#check', as: :check

end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
	before_action :authenticate_user!
	include WordsHelper
	def flashcards
		@hsk_levels =  ApplicationController.helpers.user_hsk_levels(current_user.id)
		@grammar_levels =  ApplicationController.helpers.user_grammar_levels(current_user.id)
		words = Word.where(level: @hsk_levels)
		@word = words.sort_by{|w| w.success_rate(current_user.id)}.first
		@mastered_words = WordsHelper.mastered(words, current_user.id)
		@relevant_grammar_points = GrammarPointsHelper.grammar_points_with(@word.han, @grammar_levels)
		@understandable_examples = GrammarPointsHelper.understandable_with(@relevant_grammar_points, @mastered_words)
		@word.update_sound_file
		@decompositions = @word.character_decompositions
		@word_success_rate = @word.success_rate(current_user.id).to_f.round(1) 
		@word_guess_ratio = @word.guess_ratio(current_user.id) 
	end
	def check
		@word = Word.find(params[:id])
		answer = params[:answer] || 'no_answer'
		correct_points, flash_data = @word.evaluate(answer)
		save_guess(correct_points)
		redirect_to flashcards_url, flash: flash_data
	end

	private
	def save_guess(correct_points)
		guesses = Guess.where(user: current_user, word: @word)
		if guesses.empty?
			guess = Guess.create({user: current_user, word: @word, attempts: 1, correct: correct_points})
		else
			guess = guesses.first 
			guess.update_attributes({attempts: guess.attempts + 1, correct: guess.correct + correct_points})
		end
	end
end

app/views/flashcards/flashcards.html.erb
<div class="row"> 
	<% flash.each do |name, msg| %>
		<div class="row"> 
			<div class="alert fade-in alert-<%= name %>">
				<%= msg %>
				<a href="#" data-dismiss="alert" class="close">&times</a>
			</div>
		</div>
	<% end %>
</div> 


<div class="jumbotron ">
	<div class="row"> 
		<div class="col-md-7">
			<p class="text-muted">
			Enter pinyin 
			</p>
			<h1><%= @word.han %></h1>
			<%= form_for(@word, url: check_url(id: @word.id)) do |f| %>
				<div class="field">
					<%= text_field_tag :answer, '', :autocomplete => :off %>
					<%= submit_tag 'Check', class: "btn btn-primary" %>
				</div>
			<% end %>
			<p>
			<%= audio_tag "sound.mp3", controls: true, autoplay: true %>
			</p>
		</div>

		<div class="col-md-5">

			<table class="table table-condensed">
				<thead class="text-muted small">
					<tr>
						<th>HSK level</th>
						<th>Success ratio </th>
						<th>Points/attempts </th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @word.level %></td>
						<td><%= @word_success_rate %></td>
						<td><%= @word_guess_ratio %></td>
					</tr>
				</tbody>
			</table>

			<table class="table table-condensed">
				<thead class="text-muted small">
					<tr>
						<th>Character</th>
						<th>Decomposition</th>
					</tr>
				</thead>
				<tbody>
				  <% @decompositions.each do |d| %>
					<tr>
						<td><%= d[:char] %></td>
						<td><%= d[:decomposition] %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

		</div>
	</div>
</div> 


<div class="row"> 
	<% unless @relevant_grammar_points.empty? %>
		<table class="table table-condensed">
			<thead>
				<tr>
					<th>Level</th>
					<th>Point</th>
					<th>Description</th>
				</tr>
			</thead>
			<tbody>
				<% @relevant_grammar_points.each do |gp| %>
					<tr class="info">
						<td><%= gp.level %></td>
						<td><%= gp.pattern %></td>
						<td><%= link_to gp.eng, examples_url(id:gp.id) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
	<% unless @understandable_examples.empty? %>
		<p>Sentences you can understand</p>
		<table class="table">
			<thead>
				<tr>
					<th>Point</th>
					<th>Sentence</th>
					<th>Pinyin</th>
					<th>Meaning</th>
					<th>Proportion known</th>
				</tr>
			</thead>
			<tbody>
				<% @understandable_examples.each do |h| %>
					<% example = h[:example] %>
					<% proportion = h[:proportion] %>
					<tr class="active">
						<td><%= example.grammar_point.pattern %></td>
						<td><%= example.sentence %></td>
						<td><%= example.pinyin %></td>
						<td><%= example.translation %></td>
						<td><%= proportion %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% end %>
</div> 

<% unless @mastered_words.empty? %>
	<div class="row"> 
		<div class="panel panel-warning">
			<div class="panel-heading">
				Words you probably know, HSK level <%= @hsk_levels %>, Grammar level <%= @grammar_levels %>
			</div>
			<div class="panel-body">
				<p><%= @mastered_words.join(", ") %></p>
			</div>
		</div>
	</div> 
<% end %>