config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
  resources :grammar_points
  resources :settings
  get 'grammar_points/:id/examples' => 'grammar_points#examples', as: :examples
  get 'examples' => 'grammar_points#list_examples', as: :list_examples
	

  get '/home', to:'static#home', as: :home
	root 'static#home'

  get '/network', to:'static#network'
  get '/network_HSK1', to:'static#network_HSK1'
  get '/network_HSK2', to:'static#network_HSK2'
  get '/network_HSK3', to:'static#network_HSK3'
  get '/tone_network', to:'static#tone_network'
  get '/radicals', to:'static#radicals'

  get 'grammar_tree_A1', to:'static#grammar_tree_A1'
  get 'grammar_tree_A2', to:'static#grammar_tree_A2'
  get 'grammar_tree_B1', to:'static#grammar_tree_B1'
  get 'grammar_tree_B2', to:'static#grammar_tree_B2'

  get 'flashcards/' => 'flashcards#flashcards'
  patch '/flashcards/:id/check' => 'flashcards#check', as: :check

end

app/models/setting.rb
class Setting < ActiveRecord::Base
  belongs_to :user

	validates :user_id, presence: true, uniqueness: true
	validates :hsk_level, presence: true, numericality: {less_than_or_equal_to: 6}
	validates :grammar_level, presence: true, numericality: {less_than_or_equal_to: 4}
	
	def to_hsk_levels
		(1..self.hsk_level).to_a
	end

	def to_grammar_levels
		levelmap = {'1' => %w(A1),
								'2' => %w(A1 A2),
								'3' => %w(A1 A2 B1),
								'4' => %w(A1 A2 B1 B2)}
		levelmap[self.grammar_level.to_s]
	end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	before_action :authenticate_user! 
	before_action :check_own_user, only: [:show, :edit, :update]

	def index
		settings = Setting.where(user_id: current_user.id)
		if settings.empty?
			# Create a default setting (should be done when user is created but dont want to mess with devise)
			setting = Setting.create({user_id: current_user.id})
			setting_id = setting.id
		else
			# there must be a setting for this user already, we enforce 1 setting per user so only one possible record
			setting_id = settings.first.id
		end

		params[:id] = setting_id
		set_setting
		redirect_to @setting
	end

  def show
		set_setting
  end

  def new
    @setting = Setting.new({user_id: current_user.id})
  end

  def edit
		set_setting
  end

  def create
    @setting = Setting.new({user_id: current_user.id})
    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
		set_setting
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:hsk_level, :grammar_level)
    end


    # Dont let a logged-in user edit or see others parameters but his own
		def check_own_user
      @url_setting = Setting.find(params[:id])
			redirect_to root_path unless @url_setting.user.id == current_user.id 
		end

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for(@setting) do |f| %>
  <% if @setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% @setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hsk_level %><br>
    <%= f.text_field :hsk_level %>
  </div>
  <div class="field">
    <%= f.label :grammar_level %><br>
    <%= f.text_field :grammar_level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing setting</h1>

<%= render 'form' %>

<%= link_to 'Show', @setting %> |

app/views/settings/new.html.erb
<h1>New User Setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>HSK level (1-6):</strong>
  <%= @setting.hsk_level %>
</p>

<p>
  <strong>Grammar level (1-4):</strong>
  <%= @setting.grammar_level %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> 