config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
  resources :grammar_points
  resources :settings
  get 'grammar_points/:id/examples' => 'grammar_points#examples', as: :examples
  get 'examples' => 'grammar_points#list_examples', as: :list_examples
	

  get '/home', to:'static#home', as: :home
	root 'static#home'

  get '/network', to:'static#network'
  get '/network_HSK1', to:'static#network_HSK1'
  get '/network_HSK2', to:'static#network_HSK2'
  get '/network_HSK3', to:'static#network_HSK3'
  get '/tone_network', to:'static#tone_network'
  get '/radicals', to:'static#radicals'

  get 'grammar_tree_A1', to:'static#grammar_tree_A1'
  get 'grammar_tree_A2', to:'static#grammar_tree_A2'
  get 'grammar_tree_B1', to:'static#grammar_tree_B1'
  get 'grammar_tree_B2', to:'static#grammar_tree_B2'

  get 'flashcards/' => 'flashcards#flashcards'
  patch '/flashcards/:id/check' => 'flashcards#check', as: :check

end

app/models/word.rb
class Word < ActiveRecord::Base
	validates :han, uniqueness: true
	validates :han, presence: true
	validates :pinyin, presence: true
	validates :pinyin_num, presence: true

	def to_colorless_node
		ApplicationController.helpers.springy_node(node_pairs)
	end
	def to_red_node
		pairs = node_pairs
		pairs << ['labelcolor', '#ff5533']
		ApplicationController.helpers.springy_node(pairs)
	end
	def to_node(logged_user_id)
		# set the color depending on the user's knowledge
		labelcolor = ApplicationController.helpers.gradient(success_rate(logged_user_id))
		pairs = node_pairs
		pairs << ['labelcolor', labelcolor]
		ApplicationController.helpers.springy_node(pairs)
	end
	def success_rate(logged_user_id)
		guesses = Guess.where(user_id: logged_user_id, word_id: self.id)
		if guesses.empty?
			rate = 0.0
		else
			user_guess = guesses.first
			rate = user_guess.success_rate
			# penalize the first guess to avoid immediate high rates
			if user_guess.attempts <= 2
				rate = rate.to_f / 2.0
			end
		end
		rate
	end
	def guess_ratio(logged_user_id)
		guesses = Guess.where(user_id: logged_user_id, word_id: self.id)
		if guesses.empty?
			ratio = '0/0'
		else
			guesses.first.ratio
		end
	end
	def update_sound_file
		sound_file =  File.join(Rails.root, "public", "audios", "sound.mp3")
    File.delete(sound_file) if File.exist?(sound_file)
		#  tts gem extends String class with google-tts powered mp3 file generation
		begin
			self.han.to_file("zh", sound_file)
		rescue Exception  
			# Do something meaningful (service currently unavailable)
		end
	end
	def present_in_patterns?(patterns)
		patterns.select{|p| p.include? self.han}.size > 0
	end
	def to_correct_s
			"#{self.han}  #{self.pinyin} (#{self.meaning})"
	end
	def to_wrong_s
			"#{self.han} should be  #{self.pinyin_num} (#{self.meaning})"
	end
	def evaluate(answer)
		n_answer = norm(answer.strip).to_s
		n_expected = norm(expected_pinyin)
		if n_answer == n_expected
			correct_points = 2
			flash_data = {success: "Correct: " + self.to_correct_s}
		else
			if strip_tone(n_answer) == strip_tone(n_expected)
				correct_points = 1
				flash_data = {warning: "Tone #{answer}, " + self.to_wrong_s}
			else
				correct_points = 0
				flash_data = {danger:  "Wrong #{answer}, " + self.to_wrong_s}
			end
		end
		[correct_points, flash_data]
	end
	def tone_class
		pinyin = expected_pinyin
		pinyin.gsub(/[a-zA-Z]+/,"").gsub("'","").gsub(" ","")
	end
	def characters
		self.han.split('')
	end

	def character_decompositions
		char_decompositions = []
		self.characters.each do |char|
			# NOTE decomposition could be precalculated and added to the model
			char_radicals = ApplicationController.helpers.decompose(char, list_id = 1) # 1 for detailed decomp.
			unless char_radicals.nil?
				char_decompositions << {char: char, decomposition: char_radicals.join(', ')}
			end
		end
		char_decompositions 
	end

	private
	def expected_pinyin
		pinyin = self.pinyin_num.strip
		if pinyin.include? ','
			pinyin = pinyin.split(',').first.strip 
		end
		pinyin
	end
	def strip_tone(str)
		str.gsub(/[0-5]/, '')
	end
	def norm(str)
		str.capitalize.gsub(' ','').gsub("'","").gsub('5','')
	end
	def node_pairs
		[
			['label', self.han || ''], 
			['eng', self.meaning || ''], 
			['pinyin', self.pinyin || ''], 
			['example', self.han || '']
		]	
	end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user! 

  # GET /words
  # GET /words.json
  def index
    #@words = Word.all
		@hsk_levels =  ApplicationController.helpers.user_hsk_levels(current_user.id)
    @words = Word.where(level: @hsk_levels).sort_by{|w| w.success_rate(current_user.id)}
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:han, :pinyin, :meaning, :pinyin_num)
    end
end

app/helpers/words_helper.rb
module WordsHelper
	def self.mastered(words, current_user_id)
		words.select{|w| w.success_rate(current_user_id) > 0.7}\
											.sort_by{|w| w.success_rate(current_user_id)}\
											.map{|w|w.han}
	end
	def self.single_character_words(level)
		Word.where(level: level).select{|w| w.characters.size == 1}
	end
	def self.character_alphabet(words)
		chars = []
		words.each do |w|
			w.split('').each do |ch|
				chars << ch unless chars.include? ch 
			end
		end
		chars
	end
end

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :han %><br>
    <%= f.text_field :han %>
  </div>
  <div class="field">
    <%= f.label :pinyin %><br>
    <%= f.text_field :pinyin %>
  </div>
  <div class="field">
    <%= f.label :pinyin_num %><br>
    <%= f.text_field :pinyin_num %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br>
    <%= f.text_field :meaning %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Hanzi</th>
      <th>Pinyin</th>
      <th>Meaning</th>
      <th>HSK Level</th>
      <th>Success Rate</th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
			<% rate = word.success_rate(current_user.id) %>
      <tr class="active">
        <td><%= word.han %></td>
        <td><%= word.pinyin %></td>
        <td><%= word.meaning %></td>
        <td><%= word.level %></td>
				<td style="color:<%=ApplicationController.helpers.gradient(rate)%>"><%= rate.to_f.round(2) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Han:</strong>
  <%= @word.han %>
</p>

<p>
  <strong>Pinyin:</strong>
  <%= @word.pinyin %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @word.meaning %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>