config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :words
  resources :grammar_points
  resources :settings
  get 'grammar_points/:id/examples' => 'grammar_points#examples', as: :examples
  get 'examples' => 'grammar_points#list_examples', as: :list_examples
	

  get '/home', to:'static#home', as: :home
	root 'static#home'

  get '/network', to:'static#network'
  get '/network_HSK1', to:'static#network_HSK1'
  get '/network_HSK2', to:'static#network_HSK2'
  get '/network_HSK3', to:'static#network_HSK3'
  get '/tone_network', to:'static#tone_network'
  get '/radicals', to:'static#radicals'

  get 'grammar_tree_A1', to:'static#grammar_tree_A1'
  get 'grammar_tree_A2', to:'static#grammar_tree_A2'
  get 'grammar_tree_B1', to:'static#grammar_tree_B1'
  get 'grammar_tree_B2', to:'static#grammar_tree_B2'

  get 'flashcards/' => 'flashcards#flashcards'
  patch '/flashcards/:id/check' => 'flashcards#check', as: :check

end

app/views/layouts/_footer.html.erb
<footer>
<div id="footer">
<div class="container">
	<div class="navbar-default navbar-bottom">
		<small>
		Grammar points from <%= link_to "ChineseGrammarWiki", 'http://resources.allsetlearning.com/chinese/grammar/'%>,  <%= link_to " Creative Commons Attribution/NonCommercial-Share-Alike License",   'http://creativecommons.org/licenses/by-nc-sa/3.0/' %>
		</small>
	</div>
</div>
</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
<div class="navbar-default">
	<div class="container-fluid">

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Flashcards", flashcards_path %></li>

				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Networks<span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "Grammar tree A1", grammar_tree_A1_path %></li>
					<li><%= link_to "Grammar tree A2", grammar_tree_A2_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Grammar + Words", network_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Tone Pairs", tone_network_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Vocab HSK 1", network_HSK1_path %></li>
					<li><%= link_to "Vocab HSK 2", network_HSK2_path %></li>
					<li><%= link_to "Vocab HSK 3", network_HSK3_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Radicals HSK 1+2", radicals_path %></li>
				</ul>
				</li>

				<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Lists<span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
					<li><%= link_to "Grammar Points", grammar_points_path %></li>
					<li class="divider"></li>
					<li><%= link_to "Vocab on Progress", words_path %></li>
				</ul>
				</li>

			</ul>
		</div>

		<div class="navbar">
			<ul class="nav pull-right">
				<% if user_signed_in? %>
					Logged in as <strong><%= current_user.email %></strong>.
					<%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
					<%= link_to 'Edit level', settings_path, :class => 'navbar-link' %> |
					<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
				<% else %>
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
					<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				<% end %>
			</ul>
		</div>

	</div>
</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Hanyu point by point</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div id="main-container" class="container">
			<% if notice %>
				<p class="alert alert-success"><%= notice %></p>
			 <% end %>
			 <% if alert %>
				<p class="alert alert-danger"><%= alert %></p>
			<% end %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>

	</body>
</html>